
MOVIES_DIR= "Movies"
MOVIE_DATA_DIR = "data"

DEFAULT_READ_SIZE = (1024*1024 * 32)

DEFAULT_MOVIE_NAME = "movie"
DEFAULT_MOVIE_EXTENSION = ".mkv"


TRANSCODE_DEFAULT_VCODEC = "libx264"
TRANSCODE_DEFAULT_ACODEC = "aac"